import jsPDF from 'jspdf';
import { analyzeHazardInsights } from './hazardAnalyzer';
import { formatDate } from './formatters';

/**
 * Generates a professional PDF Incident Report for a single prediction.
 */
export const generateIncidentReportPDF = (predictionItem) => {
  const doc = new jsPDF();
  const { report, prediction, confidence, executionTimeMs, timestamp } = predictionItem;
  const isSIF = prediction === 'SIF';
  const insights = analyzeHazardInsights(report, prediction);

  // Header Banner
  doc.setFillColor(255, 94, 58); // Coral #FF5E3A
  doc.rect(0, 0, 210, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('SIF AI PLATFORM — INCIDENT RISK REPORT', 14, 16);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${formatDate(timestamp || new Date().toISOString())}`, 145, 16);

  let y = 35;

  // Metadata Card
  doc.setFillColor(249, 243, 232); // Warm light beige
  doc.roundedRect(14, y, 182, 32, 3, 3, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('ASSESSMENT SUMMARY', 20, y + 10);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Risk Status: ${isSIF ? 'SIF — HIGH RISK PRECURSOR' : 'NON-SIF — LOW RISK'}`, 20, y + 18);
  doc.text(`Confidence: ${confidence ? confidence.toFixed(2) : '95.00'}%`, 20, y + 25);
  doc.text(`Latency: ${executionTimeMs || 135}ms`, 120, y + 18);
  doc.text(`Category: ${insights.primaryCategory}`, 120, y + 25);

  y += 42;

  // Incident Narrative
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('INCIDENT NARRATIVE', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);

  const splitReport = doc.splitTextToSize(`"${report}"`, 182);
  doc.text(splitReport, 14, y);
  y += splitReport.length * 5 + 8;

  // AI Explanation
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('DISTILBERT AI EXPLANATION', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  const splitExplanation = doc.splitTextToSize(insights.explanation, 182);
  doc.text(splitExplanation, 14, y);
  y += splitExplanation.length * 5 + 8;

  // Keywords & Life-Saving Rules
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('PRECURSOR KEYWORDS & LIFE-SAVING RULES', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(`Keywords: ${insights.uniqueKeywords.length > 0 ? insights.uniqueKeywords.map(k => `#${k}`).join(' ') : 'None detected'}`, 14, y);
  y += 6;
  doc.text(`Life-Saving Rule: ${insights.lifeSavingRule}`, 14, y);
  y += 10;

  // Recommended PPE & Immediate Actions
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('RECOMMENDED PPE & IMMEDIATE ACTIONS', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(`PPE Required: ${insights.recommendedPPE.join(', ')}`, 14, y);
  y += 6;

  doc.text('Immediate Actions:', 14, y);
  y += 5;
  insights.recommendedActions.forEach(action => {
    doc.text(`  •  ${action}`, 14, y);
    y += 5;
  });

  y += 4;
  doc.text('Possible Severity / Consequences:', 14, y);
  y += 5;
  insights.possibleConsequences.forEach(cons => {
    doc.text(`  -  ${cons}`, 14, y);
    y += 5;
  });

  // Footer
  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 280, 196, 280);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by SIF AI Platform (DistilBERT Transformer NLP Engine). Confidential Industrial Safety Document.', 14, 286);

  doc.save(`SIF_AI_Report_${predictionItem.id || Date.now()}.pdf`);
};

/**
 * Exports a PDF summary for a batch of predictions or history list.
 */
export const generateBatchReportPDF = (items) => {
  const doc = new jsPDF();

  doc.setFillColor(255, 94, 58);
  doc.rect(0, 0, 210, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('SIF AI PLATFORM — BATCH AUDIT REPORT', 14, 16);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, 145, 16);

  let y = 35;

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Records Analyzed: ${items.length}`, 14, y);
  y += 10;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, 182, 8, 'F');
  doc.text('Incident Report', 16, y + 5.5);
  doc.text('Prediction', 120, y + 5.5);
  doc.text('Confidence', 150, y + 5.5);
  doc.text('Status', 178, y + 5.5);
  y += 10;

  doc.setFont('helvetica', 'normal');
  items.slice(0, 35).forEach((item) => {
    const isSIF = item.prediction === 'SIF';
    const reportSnippet = item.report.length > 55 ? item.report.slice(0, 55) + '...' : item.report;
    
    doc.text(reportSnippet, 16, y);
    doc.text(item.prediction, 120, y);
    doc.text(`${item.confidence.toFixed(1)}%`, 150, y);
    doc.text(isSIF ? 'High Risk' : 'Low Risk', 178, y);

    y += 7;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  doc.save(`SIF_AI_Batch_Export_${Date.now()}.pdf`);
};
